### ISSUE TITLE
Adicionar ao repositório de bibliotecas do Arduino

### ISSUE THREAD

**Issue by FBSeletronica** [bpescarolli/74XX595_lib#2]
Sugiro que adicione a listagem de bibliotecas que podem ser instaladas diretamente na Arduino IDE.

**Comment by bpescarolli** [comment]
Gostaria de orientações de como fazer isto sou principiante ... 😁

**Comment by bpescarolli** [comment]
Este repositorio será reestruturado para poder atender as condições minimas para registar esta lib na arduino IDE.
